### ISSUE TITLE
[EPIC][Wallet][QA] Investigate the best way to implement Wallet Connect v2 in Status-Desktop

### ISSUE THREAD

**Issue by glitchminer** [status-im/desktop-qa-automation#183]
### Dev issues
Epic: https://github.com/status-im/status-desktop/issues/12301

### Tasks
 Create e2e happy paths based on Figma
 Create Negative scenarios
 Execute happy paths, minimum
 Create automation tasks in backlog

### Test summary
Description of tests and results.

**Comment by anastasiyaig** [comment]
Since this is just a prototype, no extensive testing was done in this regard. The only effort from the QA team was to assist Stefan testing the certain build on different platforms and make sure the connection established (with custom temp popup). The work continues in https://github.com/status-im/status-desktop/issues/12551 however i dont know which milestone is that. I will create Epic item here when i find out. This current Epic could be closed as no other effort is needed
