### ISSUE TITLE
Test execution continues even assert error raised

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/desktop-qa-automation#322]
Investigation task. I need to find out why tests are keep running when there is an assert raised.

**Example:** https://ci.status.im/job/status-desktop/job/e2e/job/manual/966/allure/#suites/c33b63940e2e97625a1988e6341aa93e/f1edca21ff2dfd87/

![image](https://github.com/status-im/desktop-qa-automation/assets/82375995/4b62e9d2-fadc-400d-90e0-faca24f9fb3f)

**Comment by jakubgs** [comment]
This issue will be hard to debug since we have two moving targets, the QA repo and the Desktop app versions.

Based on the timeline from Allure we can see that all the tests together laster 30 minutes and 38 seconds:

![image](https://github.com/status-im/desktop-qa-automation/assets/2212681/8d98b1cd-e4ef-4b88-b3c1-6aa3f006fa0b)

But if we look at the test execution command it lasted 53 minutes until it was terminated due to Jenkins timeout:

![image](https://github.com/status-im/desktop-qa-automation/assets/2212681/195b10e8-b648-49ed-aa85-e5c755c35351)

This indicates to me that the issue is in the test plumbing rather than in an individual test.
It's possible the test suite waits for nothing when all tests have already finished or failed.

**Comment by jakubgs** [comment]
Is see at least 3 main way to debug this:

* Bisect commits to find which change caused the timeout issue.
  - Will take a long time since currently tests timeout after 1.5h
* Bisect tests to find out if it's a specific test or any test that causes this.
  - We know `master` has this issue so we just have to find which part of it is the cause.
* Add lots of verbose logging so we can identify where the delay is coming from.
  - Will require a lot of work and might not give good results.

My recommendation would be to strip down the currently run new E2E tests to bare minimum that works every time and then gradually enable more things until something breaks or we notice a big enough delay.

**Comment by jakubgs** [comment]
This is also a stab in the dark, but a possible starting point of these issues was somewhere around here:
https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/67/

Which used `96190f3593c60688783e282328ee43eff069de3d`, though the actual cause might be a few commits before that.

Or the issue exited WAY before but was obscured by us not using the runtime test mode.

**Comment by anastasiyaig** [comment]
it is fixed in https://github.com/status-im/desktop-qa-automation/pull/326
